resources:
  - ../../base/frontend
  - ../../base/backend
  - ../../base/postgres
  - configmap.yaml

replacements:
- source:
    kind: ConfigMap
    name: radar-voluntario-config
    fieldPath: data.frontend-image
  targets:
  - select:
      kind: Deployment
      name: radar-voluntario-frontend-deployment
    fieldPaths: 
      - spec.template.spec.containers.[name=radar-voluntario-frontend-container].image
    options:
      create: true
- source:
    kind: ConfigMap
    name: radar-voluntario-config
    fieldPath: data.backend-image
  targets:
  - select:
      kind: Deployment
      name: radar-voluntario-backend-deployment
    fieldPaths: 
      - spec.template.spec.containers.[name=radar-voluntario-backend-container].image
    options:
      create: true