apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: radar-voluntario
resources:
  - ../../base/frontend
  - ../../base/backend
  - ../../base/postgres
  - configmap.yaml
  - ingress.yaml
  - pvc.yaml

patches:
  - target:
      kind: Deployment
      name: "postgres-deployment"
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts
        value:
          - name: radar-voluntario-pv
            mountPath: /var/lib/postgresql/data
      - op: add
        path: /spec/template/spec/volumes
        value: 
          - name: radar-voluntario-pv
            persistentVolumeClaim:
              claimName: radar-voluntario-pvc
replacements:
- source:
    kind: ConfigMap
    name: radar-voluntario-config
    fieldPath: data.frontend-image
  targets:
  - select:
      kind: Deployment
      name: radar-voluntario-frontend-deployment
    fieldPaths: 
      - spec.template.spec.containers.[name=radar-voluntario-frontend-container].image
    options:
      create: true
- source:
    kind: ConfigMap
    name: radar-voluntario-config
    fieldPath: data.backend-image
  targets:
  - select:
      kind: Deployment
      name: radar-voluntario-backend-deployment
    fieldPaths: 
      - spec.template.spec.containers.[name=radar-voluntario-backend-container].image
    options:
      create: true