version: '3.8'

services:
  frontend:
    container_name: radar-voluntario-frontend
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    networks:
      - radar-voluntario-network
    volumes:
      - ${FRONTEND_HOME}:/app/
      - /app/node_modules
      - /app/.git
  backend:
    container_name: radar-voluntario-backend
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    networks:
      - radar-voluntario-network
    depends_on:
      - database
  database:
    container_name: radar-voluntario-database
    env_file:
      - .env
    image: postgres:13
    restart: always
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: radar-voluntario
    networks:
      - radar-voluntario-network


networks: 
  radar-voluntario-network:
    driver: bridge
