version: '3.8'

services:
  database:
    image: postgres:13
    restart: always
    container_name: radar-voluntario-database
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: radar-voluntario
    networks:
      - radar-voluntario-network
  backend:
    container_name: radar-voluntario-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    networks:
      - radar-voluntario-network
    depends_on:
      - database

networks: 
  radar-voluntario-network:
    driver: bridge
