FROM arm64v8/node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

# If you are building your code for production
RUN npm ci --omit=dev

COPY . .
EXPOSE 8080
CMD [ "node", "server.js" ]