apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-deployment
  namespace: radar-voluntario
spec:
  replicas: 1
  # strategy:
  #   type: Recreate
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      name: node-api
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api-container
          imagePullPolicy: Always
          image: ghcr.io/antoniolago/radar-voluntario-backend:dev-1699747028 # {"$imagepolicy": "flux-system:radar-voluntario-back-img-policy"}
          ports:
            - containerPort: 3333 # Adjust the port if your Node.js app listens on a different port
          env:
            - name: GOOGLE_OAUTH_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: google_oauth_client_id
                  name: radar-voluntario-config
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: postgres-db-url
                  name: oracle-vault-radar-voluntario
            - name: BACKEND_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwt_secret
                  name: oracle-vault-radar-voluntario
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
