apiVersion: apps/v1
kind: Deployment
metadata:
  name: radar-voluntario-backend-deployment
spec:
  replicas: 1
  # strategy:
  #   type: Recreate
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      name: node-api
      labels:
        app: node-api
    spec:
      containers:
        - name: radar-voluntario-backend-container
          imagePullPolicy: Always
          image: placeholder
          ports:
            - containerPort: 3333 # Adjust the port if your Node.js app listens on a different port
          env:
            - name: GOOGLE_OAUTH_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: google-oauth-client-id
                  name: radar-voluntario-config
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: postgres-db-url
                  name: oracle-vault-radar-voluntario
            - name: BACKEND_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwt-secret
                  name: oracle-vault-radar-voluntario
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "10m"
              memory: "200Mi"
