resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./ingress.yaml

  
replacements:
  - source:
      # Replace any matches by the value of environment variable `MY_IMAGE_TAG`.
      kind: ConfigMap
      name: radar-voluntario-config
      fieldPath: data.backend_image
    targets:
      - select:
          # In each Deployment resource …
          kind: Deployment
        fieldPaths:
          # … match the image of `my-container` …
          - spec.template.spec.containers.[name=node-api-container].image
        options: 
          create: true