apiVersion: v1
kind: Service
metadata:
  name: node-api-service
  namespace: radar-voluntario
spec:
  selector:
    app: node-api
  ports:
    - protocol: TCP
      port: 80 # Use a different port if needed
      targetPort: 3000 # Match the container port
  type: ClusterIP # Use "LoadBalancer" for external access if your cluster supports it