apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: radar-voluntario-staging
resources:
  - ../../base/frontend
  - ../../base/backend
  - ../../base/postgres
  - configmap.yaml
replacements:
- source:
    kind: ConfigMap
    name: radar-voluntario-config
    fieldPath: data.image-frontend
  targets:
  - select:
      kind: Deployment
      name: radar-voluntario-frontend-deployment
    fieldPaths: 
      - spec.template.spec.containers.[name=radar-voluntario-frontend-container].image
    options:
      create: true
- source:
    kind: ConfigMap
    name: radar-voluntario-config
    fieldPath: data.image-backend
  targets:
  - select:
      kind: Deployment
      name: radar-voluntario-backend-deployment
    fieldPaths: 
      - spec.template.spec.containers.[name=radar-voluntario-backend-container].image
    options:
      create: true