apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/arm64v8/postgres:13
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: postgres-db
                  name: radar-voluntario-config
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: postgres-user
                  name: radar-voluntario-config
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: oracle-vault-radar-voluntario
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-pv
              mountPath: /var/lib/postgresql/data
              subPath: placeholder
          resources:
            limits:
              cpu: "0.4"
              memory: "500Mi"
            requests:
              cpu: "20m"
              memory: "80Mi"
      
      volumes:
        - name: postgres-pv
          persistentVolumeClaim:
            claimName: postgres-pvc
      # volumes:
      #   - name: postgres-storage
      #     persistentVolumeClaim:
      #       claimName: postgres-pvc