apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: radar-voluntario-dev
resources:
  - ../../base/frontend
  - ../../base/backend
  - ../../base/postgres
  - configmap.yaml

  
components:
  - ../../base/components