apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radar-voluntario-pvc
  namespace: radar-voluntario-development
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi