apiVersion: v1
kind: ConfigMap
metadata:
  name: radar-voluntario-config
data:
  namespace: radar-voluntario-dev
  environment: development
  host: https://radarvoluntario.duckdns.com
  backend_port: "7010"
  frontend_image: ghcr.io/antoniolago/radar-voluntario-frontend-dev
  backend_image: ghcr.io/antoniolago/radar-voluntario-backend-dev
  postgres-db: testdb
  postgres-user: testuser
  postgres-password: testpass
  google-oauth-client-id: 910904119481-m5o3q6n66b1l9bamtgh854t4c31r6kj9.apps.googleusercontent.com
