apiVersion: v1
kind: ConfigMap
metadata:
  name: radar-voluntario-config
data:
  environment: development
  host: https://radarvoluntario.duckdns.com
  backend_port: "7010"
  POSTGRES_DB: testdb
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpass
  GOOGLE_OAUTH_CLIENT_ID: 910904119481-m5o3q6n66b1l9bamtgh854t4c31r6kj9.apps.googleusercontent.com