apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: radar-voluntario-dev
resources:
  - ../base/frontend
  # - ../base/backend
  # - ../base/postgres
  - configmap.yaml
replacements:
  - source:
      # Replace any matches by the value of environment variable `MY_IMAGE_TAG`.
      kind: ConfigMap
      name: radar-voluntario-config
      fieldPath: data.host
    targets:
      - select:
          # In each Deployment resource …
          kind: Ingress
        fieldPaths:
          - spec.rules.[host=invalid.domain.com].host
        options: 
          create: true