apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  namespace: radar-voluntario
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      imagePullSecrets:
        - name: registrypullsecret
      containers:
        - name: react-app-container
          image: kustomizeplaceholder
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"