apiVersion: apps/v1
kind: Deployment
metadata:
  name: radar-voluntario-frontend-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      name: react-app
      labels:
        app: react-app
    spec:
      containers:
        - name: radar-voluntario-frontend-container
          imagePullPolicy: Always
          image: placeholder
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.2"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
