apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-app-ingress
  namespace: radar-voluntario
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-global
    acme.cert-manager.io/http01-edit-in-place: "true"
    
spec:
  tls:
    - hosts:
        - invalid.domain.com
      secretName: test-tls-secret
  rules:
    - host: invalid.domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react-app-service
                port:
                  number: 80