apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: radar-voluntario
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP # Use "LoadBalancer" for external access if your cluster supports it