name: Build & publish Docker images
on:
  push:
    tags:
      - v*
    branches: 
      - dev
  # pull_request:
  #   branches: [ "main", "dev" ]
  paths-ignore:
    - 'manifests/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: frontend/Dockerfile_deploy
            image: ghcr.io/antoniolago/radar-voluntario-frontend
            context: ./frontend
            platform: linux/amd64,linux/arm64
          - dockerfile: backend/Dockerfile_deploy
            image: ghcr.io/antoniolago/radar-voluntario-backend
            context: ./backend
            platform: linux/amd64,linux/arm64
    permissions:
      contents: read
      packages: write

    steps:
      - name: Get Branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo ::set-env name=BRANCH::$branch
      - name: Generate build ID
        id: prep
        # version=${github.event.label.name}
        # ref will be branch on branch push and tag on tagpush
        run: |
            ref=${GITHUB_REF##*/}
            sha=${GITHUB_SHA::8}
            ts=$(date +%s)
              echo "::set-output name=BUILD_ID::${ref}-${ts}"          
      - name: set env
        run: echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}
          tags: |
            ${{ steps.prep.outputs.BUILD_ID }}
            type=sha
            type=ref
            type=raw,value=latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
